console.log("1")
console.log(leftRectangleMethod(function1, 0, 5, 100))
console.log(leftRectangleMethod(function2, 0, 5, 100))
console.log("2")
console.log(rightRectangleMethod(function1, 0, 5, 100))
console.log(rightRectangleMethod(function2, 0, 5, 100))
console.log("3")
console.log(middleRectangleMethod(function1, 0, 5, 100))
console.log(middleRectangleMethod(function2, 0, 5, 100))
console.log("4")
console.log(trapezoidalMethod(function1, 0, 5, 100))
console.log(trapezoidalMethod(function2, 0, 5, 100))
console.log("5")
console.log(parabolicMethod(function1, 0, 5, 128))
console.log(parabolicMethod(function2, 0, 5, 128))

console.log("---------------------------------------------")
console.log("1")
console.log(eulerMethod(function3, 0, 5, 100))
console.log(eulerMethod(function4, 0, 5, 100))
console.log(eulerMethod(function5, 0, 5, 100))
